notifications:
  email: false
  slack: false

language: php

php:
  - 7.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar && mv wp-cli.phar wp
  - ./wp --version
  - ./wp core download
  - ls -al
  - ./wp config create --dbname="test" --dbuser="root" --dbpass="" --dbhost="127.0.0.1" --dbprefix="wp_"
  - ./wp core update-db --network

before_script:
  - composer global require hirak/prestissimo
  - composer install --dev --prefer-source --no-interaction

script:
  - ./vendor/bin/phpstan analyse -c phpstan.neon --level=5 src
  - ./vendor/bin/phpstan analyse -c phpstan.neon --level=5 tests
  - ./vendor/bin/phpcs --standard=PSR2 --extensions=php src/ tests/
  - ./vendor/bin/phpmd ./src/ text cleancode, codesize, controversial, design, naming, unusedcode
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  - bash <(curl -s https://codecov.io/bash) -t 73c0526e-22ce-4a14-a5d7-3c2261cb3ec6