notifications:
  email: false
  slack: false

language: php

php:
  - 7.1

services:
  - mysql

env:
  global:
    - TRAVIS_BUILD_DIR=/plugin

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mkdir -p wordpress
  - mkdir -p tools
  - wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -P $(pwd)/tools/
  - chmod +x tools/wp-cli.phar && mv tools/wp-cli.phar tools/wp
  - export PATH=$PATH:$(pwd)/tools
  - export PATH=vendor/bin:$PATH

install:
  - cd wordpress
  - wp core download
  - wp config create --dbname="test" --dbuser="root" --dbpass="" --dbhost="127.0.0.1" --dbprefix="wp_"
  - wp core install --url=localhost:8000 --title=Test --admin_user=lucas.loeffel --admin_password=password --admin_email=lucas@loeffel.io
  - cd $TRAVIS_BUILD_DIR
  - ls -al
  - pwd

before_script:
  - composer global require hirak/prestissimo
  - composer install --dev --prefer-source --no-interaction

script:
  - ./vendor/bin/phpstan analyse -c phpstan.neon --level=5 src
  - ./vendor/bin/phpstan analyse -c phpstan.neon --level=5 tests
  - ./vendor/bin/phpcs --standard=PSR2 --extensions=php src/ tests/
  - ./vendor/bin/phpmd ./src/ text cleancode, codesize, controversial, design, naming, unusedcode
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  - bash <(curl -s https://codecov.io/bash) -t 73c0526e-22ce-4a14-a5d7-3c2261cb3ec6